### ISSUE TITLE
design decisions

### ISSUE THREAD

**Issue by arademaker** [paulaneeley/modal#1]
Hi, do you have any documentation about the general design decisions for syntax and semantics formalization? We are doing similar work to description logics. The idea is to formalize a sequent calculus and natural deduction for ALCQ, based on the results from my thesis (http://arademaker.github.io/files/thesis.pdf) in https://github.com/arademaker/alc-lean. 

For the deduction system, from https://leanprover-community.github.io/lt2021/slides/paula-LeanTogether2021.pdf (slide 19) I see that you formalized an axiomatic system as one single definition. Right?

**Comment by paulaneeley** [comment]
Hi Alexandre,

I don't really, unfortunately. Especially since this was my first kind of
big formalization project -- I just made design decisions based on what I
understood and knew how to do at the time. That said, I would be happy to
answer any questions you may have.

You might also reach out to Bruno Bentzen. He is one of Jeremy's former
postdocs, and he also formalized some modal logics in Lean (
https://github.com/bbentzen/mpl).

Best wishes,
Paula

**Comment by arademaker** [comment]
thank you. I will contact them.
